# 실습

In [21]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
from sklearn.datasets import load_iris
Iris_dataset = load_iris()

print("Iris_dataset의 키:\n", Iris_dataset.keys())

Iris_dataset의 키:
 dict_keys(['data', 'target', 'frame', 'target_names', 'DESCR', 'feature_names', 'filename', 'data_module'])


In [ ]:
print(Iris_dataset['target_names'])

['setosa' 'versicolor' 'virginica']


In [ ]:
print(Iris_dataset['feature_names'])

['sepal length (cm)', 'sepal width (cm)', 'petal length (cm)', 'petal width (cm)']


In [ ]:
print(Iris_dataset['data'][:5])

import seaborn as sns
Iris_dataset2=sns.load_dataset('iris')
Iris_dataset2.head()

[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]]


sepal_length  sepal_width  petal_length  petal_width species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa

In [ ]:
print(Iris_dataset['target'])
print(type(Iris_dataset['target']))

[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2]
<class 'numpy.ndarray'>


In [ ]:
print(Iris_dataset['target'].shape)

(150,)


In [ ]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(Iris_dataset['data'], Iris_dataset['target'], random_state = 0)

print(X_train.shape)
print(X_test.shape)
print(type(X_train.shape))
print(type(X_test.shape))

(112, 4)
(38, 4)
<class 'tuple'>
<class 'tuple'>


In [ ]:
from google.colab  import drive
drive.mount('/content/drive')

!cd "/content/drive"
!cd "/content/drive/MyDrive/Example"

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).
/bin/bash: line 0: cd: /content/drive/MyDrive/Example: No such file or directory


In [ ]:
!mkdir "content/drive/MtDrive/Example"
!cd "content/drive/MtDrive/Example"

mkdir: cannot create directory ‘content/drive/MtDrive/Example’: No such file or directory
/bin/bash: line 0: cd: content/drive/MtDrive/Example: No such file or directory


In [ ]:
!git clone https://github.com/rickiepark/introduction_to_ml_with_python.git

fatal: destination path 'introduction_to_ml_with_python' already exists and is not an empty directory.


In [ ]:
!pip install scikit-learn==1.1.3
#import mglearn

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/


In [ ]:
Iris_dataframe=pd.DataFrame(X_train, columns=Iris_dataset.feature_names)
#pd.plotting.scatter_matrix(Iris_dataframe, c=y_train, figsize=(15,15), marker='o', hist_kwds={'bins':20}, s= 60, alpha=8, cmap=mglearn.cm3)

In [ ]:
from sklearn.neighbors import KNeighborsClassifier
knn = KNeighborsClassifier(n_neighbors=1)

In [ ]:
knn.fit(X_train, y_train)

KNeighborsClassifier(n_neighbors=1)

In [ ]:
X_new = np.array([[5,2,9,1]])
print(X_new.shape)

prediction=knn.predict(X_new)
print("prediction result", prediction)
print("target name of prediction result", Iris_dataset['target_names'][prediction])

(1, 4)
prediction result [2]
target name of prediction result ['virginica']


In [ ]:
y_pred = knn.predict(X_test)
print("prediction result of test dataset", y_pred)

prediction result of test dataset [2 1 0 2 0 2 0 1 1 1 2 1 1 1 1 0 1 1 0 0 2 1 0 0 2 0 0 1 1 0 2 1 0 2 2 1 0
 2]


In [ ]:
print("테스트 세트의 정확도: {:.3f}".format(np.mean(y_pred==y_test)))

테스트 세트의 정확도: 0.974
